version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: events-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eventsdb
      MYSQL_USER: eventsuser
      MYSQL_PASSWORD: eventspass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: sarrasoyah/eventsproject:latest
    container_name: events-app
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventsdb
      SPRING_DATASOURCE_USERNAME: eventsuser
      SPRING_DATASOURCE_PASSWORD: eventspass

volumes:
  mysql-data:
